# Generated by Django 5.0.5 on 2024-05-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_created_at_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
