# Generated by Django 5.0.5 on 2024-05-12 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
